# This is a workflow script for CI/CD

name: CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      # Downloads repo code onto the virtual machine
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Install Playwright dependencies (for Linux CI)
      - name: Install Playwright dependencies
        run: npx playwright install-deps

      # Disable Electron sandbox for CI
      - name: Disable Electron sandbox for CI
        run: echo 'ELECTRON_DISABLE_SANDBOX=true' >> $GITHUB_ENV

      # Install Dependencies
      - name: Install Dependencies
        run: yarn install

      # Run linter -> checks formatting issue
      - name: Lint
        run: yarn lint

      # Run Test script (Linux)
      - name: Run tests (Linux)
        if: runner.os == 'Linux'
        run: |
          yarn playwright install
          xvfb-run -a yarn dev &
          npx wait-on http://localhost:5173
          yarn test

      # Run Test script (macOS/Windows)
      - name: Run tests (macOS/Windows)
        if: runner.os != 'Linux'
        run: |
          yarn playwright install
          yarn dev &
          npx wait-on http://localhost:5173
          yarn test

      # Build App
      - name: Build App
        run: yarn build
